title: Lintine
email: lintine@protonmail.com
url: https://lintine.github.io
description: An international developer studio.

color:
  primary-dark: '#000000'
  links: '#219ab3'
  
footer: Lintine

social:
  - title: twitter
    url: https://twitter.com/Lintine_
  - title: youtube
    url: https://www.youtube.com/channel/UCnCAUZ6YjhZrAeeeZH1rIsQ
  - title: github
    url: https://github.com/Lintine
    
markdown: kramdown
permalink: pretty
