title: Lintine
description: An international developer studio.

remote_theme: kevadesu/grayscale-theme@v0.0.1
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
